### ISSUE TITLE
Requirement of the source data of the gif

### ISSUE THREAD

**Issue by WeichenFan** [facebookresearch/vsait#2]
Thank you for your great work!

Would you mind providing the source high-resolution data of the GTA gif images? (The current gif you provided is 456 × 256)

Looking forward to your answer!

**Comment by jdtheiss** [comment]
Thanks for your interest in our work! Here is the link to download the source GTA images (validation set 08) used in creating the gif: https://playing-for-benchmarks.org/download/.

**Comment by WeichenFan** [comment]
Thank you for your reply!
