### ISSUE TITLE
KID and mIoU

### ISSUE THREAD

**Issue by shahaf1313** [facebookresearch/vsait#3]
Hey :)
Can you please provide a link or reference to the pretrained network on Cityscapes used to evaluate mIoU and all other measures that are shown in the article?
Additionally, can you please provide code to calculate KID as appears in the article?
Thanks,
Shahaf

**Comment by jdtheiss** [comment]
Hi Shahaf,

Please see the following closed issue, but do let me know if you have further questions: https://github.com/facebookresearch/vsait/issues/1.

Best,
Justin

**Comment by shahaf1313** [comment]
Thanks a lot!
