### ISSUE TITLE
How does the code realize the binding and unbinding of image features?

### ISSUE THREAD

**Issue by xiyanbupapang** [facebookresearch/vsait#4]
I have read the code of your project in depth and your project is huge organized and excellent work! For reasons of my own ability, I was not able to find the code to encode the image as a vector as stated in the paper. How did you implement the encoding of the image as a vector and how did you implement the binding and unbinding operation? Could you please tell me the variable or function in the code that deals with this issue.On top of that, the code doesn't set the epoch to be a constant number, so how do you control the number of epochs for training? These problem has thrown me into deep confusion and I would be grateful if you could help me!

**Comment by jdtheiss** [comment]
Thanks for your interest in our work! 

We encode image patches as VSA hypervectors in two steps: feature extraction ([FeatureExtractor](https://github.com/facebookresearch/vsait/blob/c0abe5d1fce2cf965bb8af96ecdc611caeef0189/models/feature_extractor.py#L87)) and locality sensitive hashing ([LSHCat](https://github.com/facebookresearch/vsait/blob/c0abe5d1fce2cf965bb8af96ecdc611caeef0189/models/lsh.py#L81)). 

As noted in the paper, we do the binding/unbinding from one domain to another in a single step via elementwise multiplication with a "mapping hypervector" (blue-green bar shown in Fig. 3 of the [paper](https://research.facebook.com/publications/unpaired-image-translation-via-vector-symbolic-architectures/)). This mapping hypervector (called "src_to_tgt" in the code) is used twice: [for computing the VSA loss](https://github.com/facebookresearch/vsait/blob/main/models/iit.py#L177) and [for computing the GAN loss](https://github.com/facebookresearch/vsait/blob/main/models/discriminators.py#L344).

You can control the number of training iterations (i.e., batches) via the ["--max_steps"](https://github.com/facebookresearch/vsait/blob/main/options/parser.py#L61) argument.

Hope that helps!

**Comment by xiyanbupapang** [comment]
Thank you so much for your reply! As a beginner, your reply has helped me a lot and I am honored to receive your guidance~Have a nice day!

**Comment by xiyanbupapang** [comment]
I'm sorry to bother you again after such a long time! I tried to reproduce your paper's experiment on Aerial Photo → Google Map, but the resulting image cannot show the blue river water. For example, in Figure 13 of the paper, I can only get the green part in blue.
I realized that the parameter settings for Aerial Photo → Google Map in your code should be different from the GTA → Cityscapes experiment. I made modifications to the code λ = 5, and modified the kernel in LSH_ The size and structure are [32, 16, 8, 4]. What other parameters do I need to modify to reproduce your excellent results?
I hope you can guide me amidst your busy schedule, and I will be very grateful to you!
