### ISSUE TITLE
Questions about the federated data loader

### ISSUE THREAD

**Issue by xiyanbupapang** [facebookresearch/vsait#6]
In  /vsait-main/data/build.py[https://github.com/facebookresearch/vsait/blob/main/data/build.py](url), you set up a federated data loader using the following code：
` # create source/target data loaders
    source_dataloader = build_dataloader(source_cfg, is_train)
    target_dataloader = build_dataloader(target_cfg, is_train)

    # build the joint loader
    joint_dataloader = JointDataLoader(data_cfg)
    joint_dataloader.build(source_dataloader, target_dataloader, is_train)`

How are the images of the source and target domains distributed in the federated loader for the data you set up? Are the images in the loader sorted in order from source domain to target domain? Does this make sense to the model if I want to load data into generators, discriminators, and feature extractors in the order of target domain to source domain? Because I feel that my research is meaningless, I am deeply confused and wish you could guide me!

**Comment by jdtheiss** [comment]
I'm not sure that I completely understand the question, but the way that the dataloaders are set up assumes unpaired source and target datasets (i.e., each is randomized independently). If you'd like to use paired source and target datasets where the data is ingested sequentially, you'll need to change the last argument in the following line from True to False: https://github.com/facebookresearch/vsait/blob/c0abe5d1fce2cf965bb8af96ecdc611caeef0189/solver.py#L295

**Comment by xiyanbupapang** [comment]
Sorry my description is not clear enough to create ambiguity, but your answer gives me a great idea for my research! I think I need to study harder. Thank you very much for your patience in replying to me every time！

**Comment by jdtheiss** [comment]
No worries, feel free to reopen the issue if you have further questions.
